Repository informatics-isi-edu/chaise, pull requests merged in 2018-06, with the labels that each got.

#1544 recordedit error check login state first
  common/authen.js
  common/errors.js
  common/recordCreate.js
Labels: bug

#1547 Test Case : Add Pure And Binary Testcases for Inline #1409
  common/styles/app.css
  common/templates/record.html
  record/record.app.js
  test/e2e/data_setup/data/product/accommodation_image_assoc.json
  test/e2e/data_setup/schema/record/product.json
  test/e2e/specs/all-features-confirmation/record/presentation.spec.js
Labels: e2e Test

#1550 Add text to terminal error#1508
  common/errors.js
Labels: e2e Test

#1554 Added Login Link in Session Alert #1530
  common/alerts.js
  common/templates/alerts.html
  common/utils.js
Labels: enhancement

#1561 Improve URL Limitation Handling In Recordset
  common/alerts.js
  common/ellipses.js
  common/faceting.js
  common/modal.js
  common/styles/app.css
  common/table.js
  common/templates/ellipses.html
  common/templates/recordset.html
  common/templates/recordsetSelectFaceting.html
  common/templates/searchPopup.modal.html
  common/templates/table.html
  common/utils.js
  test/e2e/data_setup/data/faceting/main.json
  test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js
Labels: enhancement, recordset

#1576 moved Filetype validation
  common/recordCreate.js
  common/templates/upload.html
  common/upload.js
  common/utils.js
  common/validators.js
  test/e2e/specs/all-features-confirmation/recordedit/add.spec.js
Labels: bug
